// ─────────────────────────────────────────────────────────────────────────────
//  Contracts Module — Employment Contract Generation
//  SA Labour Law Compliant (BCEA, LRA, EEA, POPIA)
// ─────────────────────────────────────────────────────────────────────────────

const Contracts = {

  // ─── Main Render ────────────────────────────────────────────────────────────
  render: function (container) {
    window.DB.contracts = window.DB.contracts || [];
    const contracts = window.DB.contracts;

    container.innerHTML = `
      <div class="page-title-box" style="display:flex;justify-content:space-between;align-items:center;margin-bottom:24px;">
        <div>
          <h2><i class="fas fa-file-contract"></i> Employment Contracts</h2>
          <div style="color:var(--gray-500)">Generate and manage SA-compliant employment contracts</div>
        </div>
        <button class="btn btn-primary" onclick="Contracts.showGenerateModal()">
          <i class="fas fa-plus"></i> Generate Contract
        </button>
      </div>

      <!-- KPI Strip -->
      <div class="grid-3" style="margin-bottom:24px;">
        <div class="kpi-card" style="border-left:4px solid var(--success)">
          <div class="kpi-label">Permanent</div>
          <div class="kpi-value">${contracts.filter(c => c.contractType === 'Permanent').length}</div>
        </div>
        <div class="kpi-card" style="border-left:4px solid var(--warning)">
          <div class="kpi-label">Contractor</div>
          <div class="kpi-value">${contracts.filter(c => c.contractType === 'Contractor').length}</div>
        </div>
        <div class="kpi-card" style="border-left:4px solid var(--info)">
          <div class="kpi-label">Part Time</div>
          <div class="kpi-value">${contracts.filter(c => c.contractType === 'Part Time').length}</div>
        </div>
      </div>

      <!-- Contracts Table -->
      <div class="card">
        <div class="card-header">
          <h4 class="card-title">Generated Contracts</h4>
          <div class="search-box">
            <input type="text" class="search-input" placeholder="Search contracts..."
              onkeyup="Contracts.filterTable(this.value)">
          </div>
        </div>
        <div class="table-responsive">
          <table id="contractsTable">
            <thead>
              <tr>
                <th>Employee</th>
                <th>ID Number</th>
                <th>Contract Type</th>
                <th>Generated On</th>
                <th>Generated By</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              ${contracts.length ? contracts.map(c => `
                <tr>
                  <td>
                    <div style="font-weight:600;font-size:0.88rem">${c.firstName} ${c.lastName}</div>
                    <div style="font-size:0.75rem;color:var(--gray-500)">${c.email}</div>
                  </td>
                  <td style="font-family:monospace;font-size:0.82rem">${c.idNumber}</td>
                  <td>
                    <span class="badge badge-${c.contractType === 'Permanent' ? 'success' : c.contractType === 'Contractor' ? 'warning' : 'info'}">
                      ${c.contractType}
                    </span>
                  </td>
                  <td style="font-size:0.85rem">${c.generatedOn}</td>
                  <td style="font-size:0.85rem">${c.generatedBy || 'Admin'}</td>
                  <td>
                    <div style="display:flex;gap:4px;">
                      <button class="btn-icon" title="View / Print" onclick="Contracts.viewContract(${c.id})">
                        <i class="fas fa-eye"></i>
                      </button>
                      <button class="btn-icon text-danger" title="Delete" onclick="Contracts.deleteContract(${c.id})">
                        <i class="fas fa-trash"></i>
                      </button>
                    </div>
                  </td>
                </tr>
              `).join('') : `
                <tr>
                  <td colspan="6">
                    <div class="empty-state" style="padding:40px;">
                      <div class="empty-state-icon"><i class="fas fa-file-contract"></i></div>
                      <div class="empty-state-title">No Contracts Generated</div>
                      <div class="empty-state-desc">Click "Generate Contract" to create your first employment contract.</div>
                    </div>
                  </td>
                </tr>`}
            </tbody>
          </table>
        </div>
      </div>
    `;
  },

  filterTable: function (query) {
    const q = query.toLowerCase();
    document.querySelectorAll('#contractsTable tbody tr').forEach(row => {
      row.style.display = row.textContent.toLowerCase().includes(q) ? '' : 'none';
    });
  },

  // ─── Generate Modal ──────────────────────────────────────────────────────────
  showGenerateModal: function () {
    const empOptions = (window.DB.employees || [])
      .filter(e => e.status === 'Active')
      .map(e => `<option value="${e.id}">${e.firstName} ${e.lastName} — ${e.position || ''}</option>`)
      .join('');

    const html = `
      <div class="card" style="width:100%;max-width:740px;margin:auto;max-height:92vh;overflow-y:auto;">
        <div class="card-header">
          <h3><i class="fas fa-file-contract" style="color:var(--primary)"></i> &nbsp;Generate Employment Contract</h3>
          <button class="btn btn-outline btn-sm" onclick="closeModal('contractGenerateModal')">
            <i class="fas fa-times"></i>
          </button>
        </div>
        <div class="card-body">

          <!-- Quick-fill from existing employee -->
          <div class="alert alert-info" style="margin-bottom:16px;font-size:0.83rem;">
            <i class="fas fa-magic"></i> &nbsp;
            <strong>Quick fill:</strong> Select an existing employee to auto-populate the fields, or fill in manually for a new hire.
          </div>
          <div class="form-group" style="margin-bottom:20px;">
            <label class="form-label">Auto-fill from Existing Employee (optional)</label>
            <select class="form-control" id="ct_autofill" onchange="Contracts.autoFill(this.value)">
              <option value="">— fill manually —</option>
              ${empOptions}
            </select>
          </div>

          <div style="height:1px;background:var(--gray-200);margin-bottom:20px;"></div>

          <!-- Form Fields -->
          <div class="grid-2">
            <div class="form-group">
              <label class="form-label">First Name <span style="color:var(--danger)">*</span></label>
              <input type="text" id="ct_firstName" class="form-control" placeholder="e.g. Thabo">
            </div>
            <div class="form-group">
              <label class="form-label">Last Name <span style="color:var(--danger)">*</span></label>
              <input type="text" id="ct_lastName" class="form-control" placeholder="e.g. Mokoena">
            </div>
            <div class="form-group">
              <label class="form-label">ID Number <span style="color:var(--danger)">*</span></label>
              <input type="text" id="ct_idNumber" class="form-control" placeholder="13-digit SA ID Number" maxlength="13">
            </div>
            <div class="form-group">
              <label class="form-label">Date of Birth <span style="color:var(--danger)">*</span></label>
              <input type="date" id="ct_dob" class="form-control">
            </div>
            <div class="form-group">
              <label class="form-label">Gender <span style="color:var(--danger)">*</span></label>
              <select id="ct_gender" class="form-control">
                <option value="">Select gender</option>
                <option value="Male">Male</option>
                <option value="Female">Female</option>
                <option value="Other">Other / Prefer not to say</option>
              </select>
            </div>
            <div class="form-group">
              <label class="form-label">Contract Type <span style="color:var(--danger)">*</span></label>
              <select id="ct_contractType" class="form-control" onchange="Contracts.showTypePreview(this.value)">
                <option value="">Select contract type</option>
                <option value="Permanent">Permanent Employment</option>
                <option value="Contractor">Independent Contractor</option>
                <option value="Part Time">Part-Time Employment</option>
              </select>
            </div>
            <div class="form-group">
              <label class="form-label">Email Address <span style="color:var(--danger)">*</span></label>
              <input type="email" id="ct_email" class="form-control" placeholder="employee@company.com">
            </div>
            <div class="form-group">
              <label class="form-label">Phone Number <span style="color:var(--danger)">*</span></label>
              <input type="tel" id="ct_phone" class="form-control" placeholder="+27 82 000 0000">
            </div>
          </div>

          <div class="form-group">
            <label class="form-label">Physical Address <span style="color:var(--danger)">*</span></label>
            <textarea id="ct_address" class="form-control" rows="2"
              placeholder="e.g. 45 Oak Avenue, Randburg, Johannesburg, 2194"></textarea>
          </div>

          <!-- Contract type preview badge -->
          <div id="ct_typePreview" style="display:none;margin-bottom:16px;"></div>

          <button class="btn btn-primary" style="width:100%;margin-top:8px;font-size:0.93rem;padding:11px;"
            onclick="Contracts.generateContract()">
            <i class="fas fa-file-contract"></i> &nbsp; Generate & View Contract
          </button>
        </div>
      </div>
    `;
    window.showModal('contractGenerateModal', html);
  },

  autoFill: function (empId) {
    if (!empId) return;
    const emp = window.DB.employees.find(e => e.id == empId);
    if (!emp) return;
    const set = (id, val) => { const el = document.getElementById(id); if (el && val) el.value = val; };
    set('ct_firstName', emp.firstName);
    set('ct_lastName', emp.lastName);
    set('ct_idNumber', (emp.idNumber || '').replace(/\s/g, ''));
    set('ct_dob', emp.dateOfBirth);
    set('ct_gender', emp.gender);
    set('ct_email', emp.email);
    set('ct_phone', emp.phone);
    set('ct_address', emp.address);
    // Map employment type
    const typeMap = { 'Permanent': 'Permanent', 'Contract': 'Contractor', 'Part-Time': 'Part Time' };
    set('ct_contractType', typeMap[emp.employmentType] || '');
    if (emp.employmentType) Contracts.showTypePreview(typeMap[emp.employmentType] || '');
  },

  showTypePreview: function (type) {
    const preview = document.getElementById('ct_typePreview');
    if (!preview) return;
    const descriptions = {
      'Permanent': { color: 'success', icon: 'user-check', text: 'Permanent employment — full BCEA benefits apply including annual leave, sick leave, notice periods, and UIF.' },
      'Contractor': { color: 'warning', icon: 'briefcase', text: 'Independent contractor — no employment relationship; contractor is responsible for own tax obligations. IP and confidentiality clauses apply.' },
      'Part Time': { color: 'info', icon: 'clock', text: 'Part-time employment — pro-rata BCEA entitlements apply. Statutory deductions (PAYE, UIF) still apply.' }
    };
    const d = descriptions[type];
    if (!d) { preview.style.display = 'none'; return; }
    preview.style.display = 'block';
    preview.innerHTML = `
      <div class="alert alert-${d.color}" style="font-size:0.82rem;">
        <i class="fas fa-${d.icon}"></i> &nbsp; <strong>${type}:</strong> ${d.text}
      </div>`;
  },

  generateContract: function () {
    const get = id => (document.getElementById(id)?.value || '').trim();
    const firstName    = get('ct_firstName');
    const lastName     = get('ct_lastName');
    const idNumber     = get('ct_idNumber');
    const dob          = get('ct_dob');
    const gender       = get('ct_gender');
    const contractType = get('ct_contractType');
    const email        = get('ct_email');
    const phone        = get('ct_phone');
    const address      = get('ct_address');

    if (!firstName || !lastName || !idNumber || !dob || !gender || !contractType || !email || !phone || !address) {
      window.Toast.show('Please fill in all required fields (*)', 'warning');
      return;
    }

    if (idNumber.length !== 13 || !/^\d+$/.test(idNumber)) {
      window.Toast.show('ID Number must be exactly 13 digits', 'warning');
      return;
    }

    const contract = {
      id: Date.now(),
      firstName, lastName, idNumber, dob, gender,
      contractType, email, phone, address,
      generatedOn: new Date().toLocaleDateString('en-ZA'),
      generatedBy: window.currentUser?.name || 'Admin',
      company: window.DB.settings?.companyName || 'Acme Corp SA'
    };

    window.DB.contracts = window.DB.contracts || [];
    window.DB.contracts.unshift(contract);
    window.DB.save();

    window.Toast.show(`${contractType} contract generated for ${firstName} ${lastName}`, 'success');
    closeModal('contractGenerateModal');

    // Re-render list, then open contract viewer
    this.render(document.getElementById('content'));
    setTimeout(() => this.viewContractData(contract), 200);
  },

  // ─── Contract Viewer ─────────────────────────────────────────────────────────
  viewContract: function (id) {
    const contract = (window.DB.contracts || []).find(c => c.id === id);
    if (!contract) { window.Toast.show('Contract not found', 'warning'); return; }
    this.viewContractData(contract);
  },

  viewContractData: function (contract) {
    const backdrop = document.createElement('div');
    backdrop.className = 'modal-backdrop';
    backdrop.onclick = (e) => { if (e.target === backdrop) backdrop.remove(); };
    backdrop.innerHTML = `
      <div class="modal-content payslip-modal" onclick="event.stopPropagation()">
        <div class="modal-header">
          <h3><i class="fas fa-file-contract" style="color:var(--primary)"></i>
            &nbsp;${contract.contractType} Contract — ${contract.firstName} ${contract.lastName}
          </h3>
          <button onclick="this.closest('.modal-backdrop').remove()">×</button>
        </div>
        <div class="modal-body">
          ${this.buildContractHTML(contract)}
        </div>
        <div class="modal-footer">
          <button class="btn btn-outline" onclick="this.closest('.modal-backdrop').remove()">Close</button>
          <button class="btn btn-primary" onclick="window.print()">
            <i class="fas fa-print"></i> Print / Save PDF
          </button>
        </div>
      </div>
    `;
    document.body.appendChild(backdrop);
  },

  // ─── Contract HTML Builder ───────────────────────────────────────────────────
  buildContractHTML: function (contract) {
    const company  = contract.company || window.DB.settings?.companyName || 'Acme Corp SA';
    const today    = new Date().toLocaleDateString('en-ZA', { day: 'numeric', month: 'long', year: 'numeric' });
    const typeMap  = { Permanent: this._permanentClauses, Contractor: this._contractorClauses, 'Part Time': this._partTimeClauses };
    const clauses  = (typeMap[contract.contractType] || this._permanentClauses).call(this);
    const badgeColor = contract.contractType === 'Permanent' ? '#059669' : contract.contractType === 'Contractor' ? '#d97706' : '#0284c7';

    return `
      <div style="padding:40px 48px;background:#fff;font-family:'Arial',sans-serif;color:#1e293b;
                  max-width:820px;margin:0 auto;line-height:1.75;font-size:14px;">

        <!-- Letterhead -->
        <div style="display:flex;justify-content:space-between;align-items:flex-start;
                    border-bottom:3px solid #4f46e5;padding-bottom:20px;margin-bottom:32px;">
          <div>
            <div style="font-size:1.5rem;font-weight:800;color:#4f46e5;letter-spacing:-0.5px;">${company}</div>
            <div style="font-size:0.8rem;color:#64748b;margin-top:2px;">Human Resources Department</div>
          </div>
          <div style="text-align:right;">
            <div style="display:inline-block;background:${badgeColor};color:#fff;padding:4px 14px;
                        border-radius:20px;font-size:0.78rem;font-weight:700;letter-spacing:0.5px;margin-bottom:6px;">
              ${contract.contractType.toUpperCase()} CONTRACT
            </div>
            <div style="font-size:0.82rem;color:#475569;">Date: <strong>${today}</strong></div>
            <div style="font-size:0.78rem;color:#94a3b8;margin-top:2px;">
              Ref: CT-${String(contract.id).slice(-6)}
            </div>
          </div>
        </div>

        <!-- Section 1: Parties -->
        <div style="margin-bottom:28px;">
          ${this._sectionHeading('1', 'PARTIES TO THIS AGREEMENT')}
          <table style="width:100%;border-collapse:collapse;font-size:0.88rem;">
            <tr>
              <td style="padding:5px 0;color:#475569;width:180px;"><strong>Employer ("Company")</strong></td>
              <td style="padding:5px 0;">${company}</td>
            </tr>
            <tr>
              <td style="padding:5px 0;color:#475569;"><strong>Employee Full Name</strong></td>
              <td style="padding:5px 0;">${contract.firstName} ${contract.lastName}</td>
            </tr>
            <tr>
              <td style="padding:5px 0;color:#475569;"><strong>South African ID No.</strong></td>
              <td style="padding:5px 0;font-family:monospace;letter-spacing:1px;">${contract.idNumber}</td>
            </tr>
            <tr>
              <td style="padding:5px 0;color:#475569;"><strong>Date of Birth</strong></td>
              <td style="padding:5px 0;">${contract.dob}</td>
            </tr>
            <tr>
              <td style="padding:5px 0;color:#475569;"><strong>Gender</strong></td>
              <td style="padding:5px 0;">${contract.gender}</td>
            </tr>
            <tr>
              <td style="padding:5px 0;color:#475569;"><strong>Email Address</strong></td>
              <td style="padding:5px 0;">${contract.email}</td>
            </tr>
            <tr>
              <td style="padding:5px 0;color:#475569;"><strong>Phone Number</strong></td>
              <td style="padding:5px 0;">${contract.phone}</td>
            </tr>
            <tr>
              <td style="padding:5px 0;color:#475569;"><strong>Residential Address</strong></td>
              <td style="padding:5px 0;">${contract.address}</td>
            </tr>
          </table>
        </div>

        <!-- Type-specific clauses (2-6) -->
        ${clauses}

        <!-- Section 7: Statutory Deductions -->
        <div style="margin-bottom:28px;">
          ${this._sectionHeading('7', 'STATUTORY DEDUCTIONS')}
          <p>The Employee acknowledges that the Company is legally required to deduct the following from remuneration:</p>
          <ul style="margin:8px 0 0 22px;line-height:2;">
            <li>Income Tax (PAYE) — Income Tax Act 58 of 1962</li>
            <li>Unemployment Insurance Fund (UIF) — 1% of remuneration (employee) and 1% (employer), capped at the legislated monthly ceiling</li>
            <li>Skills Development Levy (SDL) — 1% of gross payroll (employer-only)</li>
            <li>Any court-ordered garnishee or maintenance orders</li>
            <li>Agreed pension/provident fund contributions</li>
          </ul>
        </div>

        <!-- Section 8: POPIA -->
        <div style="margin-bottom:28px;">
          ${this._sectionHeading('8', 'PROTECTION OF PERSONAL INFORMATION (POPIA)')}
          <p>The Company processes the Employee's personal information strictly in accordance with the Protection of Personal Information Act 4 of 2013 (POPIA). Personal data is collected and processed solely for legitimate employment purposes, including payroll administration, statutory reporting, benefits management, and HR compliance. By signing this agreement, the Employee provides informed consent to such processing. The Employee has the right to access, correct, or object to processing of their personal information by submitting a written request to the HR department.</p>
        </div>

        <!-- Section 9: Confidentiality -->
        <div style="margin-bottom:28px;">
          ${this._sectionHeading('9', 'CONFIDENTIALITY & NON-DISCLOSURE')}
          <p>The Employee undertakes to hold strictly confidential all proprietary information, trade secrets, client data, financial information, business strategies, and personnel records belonging to the Company, its clients, and its associates. This obligation survives termination of this agreement. Unauthorised disclosure constitutes a material breach and may result in disciplinary action and civil legal proceedings.</p>
        </div>

        <!-- Section 10: Governing Law -->
        <div style="margin-bottom:36px;">
          ${this._sectionHeading('10', 'GOVERNING LAW & DISPUTE RESOLUTION')}
          <p>This agreement is governed by the laws of the Republic of South Africa, including:</p>
          <ul style="margin:8px 0 0 22px;line-height:2;">
            <li>Basic Conditions of Employment Act 75 of 1997 (BCEA)</li>
            <li>Labour Relations Act 66 of 1995 (LRA)</li>
            <li>Employment Equity Act 55 of 1998 (EEA)</li>
            <li>Compensation for Occupational Injuries and Diseases Act 130 of 1993 (COIDA)</li>
          </ul>
          <p style="margin-top:10px;">Any disputes shall be referred first to internal grievance procedures, then to the Commission for Conciliation, Mediation and Arbitration (CCMA), and thereafter to the Labour Court as applicable.</p>
        </div>

        <!-- Signature Block -->
        <div style="background:#f8fafc;border:1px solid #e2e8f0;border-radius:10px;padding:24px;margin-bottom:32px;">
          <div style="font-weight:700;font-size:0.9rem;color:#334155;margin-bottom:20px;text-transform:uppercase;letter-spacing:0.5px;">
            Acceptance & Signatures
          </div>
          <div style="display:grid;grid-template-columns:1fr 1fr;gap:48px;">
            <div>
              <div style="font-size:0.82rem;color:#64748b;margin-bottom:4px;">Employee</div>
              <div style="font-weight:600;margin-bottom:2px;">${contract.firstName} ${contract.lastName}</div>
              <div style="border-top:2px solid #334155;margin-top:44px;padding-top:6px;">
                <div style="font-size:0.78rem;color:#94a3b8;">Signature &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Date: ___________</div>
              </div>
            </div>
            <div>
              <div style="font-size:0.82rem;color:#64748b;margin-bottom:4px;">Authorised Signatory</div>
              <div style="font-weight:600;margin-bottom:2px;">${company}</div>
              <div style="border-top:2px solid #334155;margin-top:44px;padding-top:6px;">
                <div style="font-size:0.78rem;color:#94a3b8;">Signature &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Date: ___________</div>
              </div>
            </div>
          </div>
        </div>

        <!-- Footer -->
        <div style="text-align:center;font-size:0.75rem;color:#94a3b8;border-top:1px solid #e2e8f0;padding-top:14px;">
          Generated by HR &amp; Payroll Management System on ${today} &nbsp;|&nbsp; Document Ref: CT-${String(contract.id).slice(-6)}
          &nbsp;|&nbsp; This document is legally binding once signed by both parties.
        </div>
      </div>`;
  },

  // ─── Section Heading Helper ───────────────────────────────────────────────────
  _sectionHeading: function (num, title) {
    return `<h3 style="font-size:0.92rem;font-weight:700;color:#4f46e5;text-transform:uppercase;
                       letter-spacing:0.4px;border-bottom:2px solid #e2e8f0;padding-bottom:6px;
                       margin-bottom:14px;">${num}. ${title}</h3>`;
  },

  // ─── Permanent Clauses ────────────────────────────────────────────────────────
  _permanentClauses: function () {
    return `
      <div style="margin-bottom:28px;">
        ${this._sectionHeading('2', 'NATURE OF EMPLOYMENT')}
        <p>The Employee is employed on a <strong>permanent, indefinite basis</strong> subject to the terms herein, the Company's policies and procedures manual, and the provisions of the BCEA and LRA. This agreement supersedes any prior verbal or written understandings between the parties.</p>
      </div>
      <div style="margin-bottom:28px;">
        ${this._sectionHeading('3', 'COMMENCEMENT & PROBATIONARY PERIOD')}
        <p>Employment commences on the date of signature. The Employee shall serve a probationary period of <strong>three (3) calendar months</strong>. During this period, performance, conduct, and general suitability will be assessed. The probationary period may be extended by up to a further three (3) months at the Company's discretion with written notice. Upon successful completion, employment is confirmed as permanent.</p>
      </div>
      <div style="margin-bottom:28px;">
        ${this._sectionHeading('4', 'NOTICE OF TERMINATION')}
        <p>Either party may terminate this agreement by giving notice in writing as follows:</p>
        <ul style="margin:8px 0 0 22px;line-height:2;">
          <li>During probation: <strong>One (1) week</strong> written notice</li>
          <li>After probation — less than 1 year of service: <strong>Two (2) weeks</strong> written notice</li>
          <li>One (1) year or more of service: <strong>Four (4) weeks</strong> written notice</li>
        </ul>
        <p style="margin-top:10px;">The Company reserves the right to summarily dismiss the Employee without notice for serious misconduct as defined in Schedule 8 of the LRA and the Company's Disciplinary Code and Procedure.</p>
      </div>
      <div style="margin-bottom:28px;">
        ${this._sectionHeading('5', 'LEAVE ENTITLEMENTS (BCEA COMPLIANT)')}
        <p>The Employee is entitled to the following leave per leave cycle:</p>
        <ul style="margin:8px 0 0 22px;line-height:2;">
          <li><strong>Annual Leave:</strong> 15 working days per annum, accrued at 1.25 days per month</li>
          <li><strong>Sick Leave:</strong> 30 days in a three-year leave cycle (6 days in the first six months)</li>
          <li><strong>Family Responsibility Leave:</strong> 3 days per annum (birth, death, illness of family member)</li>
          <li><strong>Maternity Leave:</strong> 4 consecutive months unpaid (BCEA s 25)</li>
          <li><strong>Parental Leave:</strong> 10 consecutive days unpaid (BCEA s 25A)</li>
        </ul>
        <p style="margin-top:8px;">Leave must be applied for in advance and is subject to operational requirements. Sick leave exceeding two (2) consecutive days requires a medical certificate from a registered medical practitioner.</p>
      </div>
      <div style="margin-bottom:28px;">
        ${this._sectionHeading('6', 'REMUNERATION & BENEFITS')}
        <p>The Employee's remuneration is as agreed in the accompanying offer letter and is paid <strong>monthly by electronic funds transfer (EFT)</strong> into the Employee's nominated bank account. Salary is subject to annual review at the Company's discretion. The Employee may be eligible to participate in the Company's medical aid scheme, pension/provident fund, and other benefit programmes in accordance with the applicable rules of those schemes.</p>
      </div>`;
  },

  // ─── Contractor Clauses ───────────────────────────────────────────────────────
  _contractorClauses: function () {
    return `
      <div style="margin-bottom:28px;">
        ${this._sectionHeading('2', 'NATURE OF ENGAGEMENT')}
        <p>The Contractor is engaged as an <strong>independent contractor</strong> and not as an employee. This agreement does not constitute an employment relationship under the LRA, BCEA, or any other labour legislation. The Contractor is solely responsible for their own tax affairs, including registration as a provisional taxpayer with SARS and submission of provisional and annual income tax returns.</p>
      </div>
      <div style="margin-bottom:28px;">
        ${this._sectionHeading('3', 'CONTRACT DURATION & TERMINATION')}
        <p>This engagement commences on the agreed start date and will continue until the agreed end date or project completion, whichever occurs first. Either party may terminate with <strong>two (2) weeks' written notice</strong>. The Company may terminate immediately and without notice in the event of a material breach of this agreement, non-performance, or conduct that would constitute gross misconduct in an employment context.</p>
      </div>
      <div style="margin-bottom:28px;">
        ${this._sectionHeading('4', 'FEES & PAYMENT')}
        <p>The Contractor shall be remunerated at the agreed daily or monthly rate as specified in the accompanying Statement of Work or Purchase Order. Valid tax invoices must be submitted by the last working day of each month. Payment will be processed within <strong>30 days of receipt</strong> of a valid invoice. The Company is not obligated to provide UIF contributions, medical aid, provident fund, or any other employee benefits. The Contractor is responsible for all applicable taxes, including VAT if registered.</p>
      </div>
      <div style="margin-bottom:28px;">
        ${this._sectionHeading('5', 'INTELLECTUAL PROPERTY')}
        <p>All work product, deliverables, source code, designs, documentation, methodologies, and any other intellectual property created by the Contractor in the course of this engagement shall vest immediately and exclusively in the Company. The Contractor irrevocably assigns all rights, title, and interest in such intellectual property to the Company and shall execute any further instruments required to perfect such assignment at the Company's request and cost.</p>
      </div>
      <div style="margin-bottom:28px;">
        ${this._sectionHeading('6', 'INDEPENDENT OPERATIONS & RESTRAINT')}
        <p>The Contractor may work for other clients during the term of this agreement provided it does not create a conflict of interest or result in the disclosure of the Company's confidential information. The Contractor shall disclose any actual or potential conflict of interest in writing. The Contractor agrees not to solicit the Company's employees, clients, or suppliers for a period of 12 months following termination of this agreement.</p>
      </div>`;
  },

  // ─── Part-Time Clauses ────────────────────────────────────────────────────────
  _partTimeClauses: function () {
    return `
      <div style="margin-bottom:28px;">
        ${this._sectionHeading('2', 'NATURE OF EMPLOYMENT')}
        <p>The Employee is employed on a <strong>part-time basis</strong>. In accordance with section 83A of the BCEA, the Employee enjoys the same pro-rated statutory rights as permanent full-time employees. All entitlements under the BCEA and LRA apply on a pro-rata basis relative to the Employee's agreed working hours in proportion to a standard 45-hour week.</p>
      </div>
      <div style="margin-bottom:28px;">
        ${this._sectionHeading('3', 'HOURS OF WORK')}
        <p>The Employee's working hours, days, and schedule are as agreed with the direct Line Manager and recorded in the accompanying work schedule. Working hours shall not exceed the statutory maximums stipulated in the BCEA. Any overtime required must be authorised in advance by the Line Manager and will be compensated at the applicable overtime rate (1.5× for overtime, 2× for Sundays and public holidays) as required by the BCEA.</p>
      </div>
      <div style="margin-bottom:28px;">
        ${this._sectionHeading('4', 'NOTICE OF TERMINATION')}
        <p>Either party may terminate this agreement by giving written notice as follows:</p>
        <ul style="margin:8px 0 0 22px;line-height:2;">
          <li>Less than six (6) months of service: <strong>One (1) week</strong> written notice</li>
          <li>Six (6) months to one (1) year: <strong>Two (2) weeks</strong> written notice</li>
          <li>One (1) year or more: <strong>Four (4) weeks</strong> written notice</li>
        </ul>
      </div>
      <div style="margin-bottom:28px;">
        ${this._sectionHeading('5', 'PRO-RATA LEAVE ENTITLEMENTS')}
        <p>The Employee's leave entitlements are calculated proportionally to their agreed working hours relative to a 45-hour full working week. The statutory minimum entitlements under the BCEA apply in all cases. Sick leave in excess of two consecutive days requires a medical certificate. Annual leave accrues monthly and must be taken within six months of the end of each leave cycle unless otherwise agreed in writing.</p>
      </div>
      <div style="margin-bottom:28px;">
        ${this._sectionHeading('6', 'REMUNERATION')}
        <p>The Employee shall be remunerated at the agreed hourly or pro-rata monthly rate as specified in the offer letter. Salary is paid monthly by EFT. All applicable statutory deductions (PAYE, UIF) will be made. The Employee is eligible for Company benefit schemes on a pro-rata basis as per the applicable scheme rules and Company policy.</p>
      </div>`;
  },

  // ─── Delete ──────────────────────────────────────────────────────────────────
  deleteContract: function (id) {
    const c = (window.DB.contracts || []).find(x => x.id === id);
    if (!c) return;
    window.showConfirmation(
      'Delete Contract?',
      `Are you sure you want to permanently delete the contract for <strong>${c.firstName} ${c.lastName}</strong>? This cannot be undone.`,
      () => {
        window.DB.contracts = window.DB.contracts.filter(x => x.id !== id);
        window.DB.save();
        window.Toast.show('Contract deleted', 'success');
        this.render(document.getElementById('content'));
      }
    );
  }
};

window.renderContracts = function (container) {
  Contracts.render(container);
};